[[profile]]
name = "default"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
match = "eDP-1"
enable = true
mode = {width = 1366,height = 768,refresh = 60}
position = {x=0, y=0}
